on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: .
        submodules: recursive
    - name: Run script
      run: ./build.ps1
